import type { LifestylePreset, LifestyleId } from './lifestyle'
import type { Region } from '../config/regions'

type LifestylePresetMap = Record<Exclude<LifestyleId, 'custom'>, LifestylePreset>

export const LIFESTYLE_PRESETS_PH_MANILA: LifestylePresetMap = {
  frugal: {
    id: 'frugal',
    name: 'Frugal',
    emoji: 'Saver',
    description: 'Entry-level Manila setup with tight rent control and modest savings.',
    tagline: 'Lean city budget',
    annualIncome: 300000,
    annualExpense: 180000,
    annualContribution: 60000,
    savingsRate: 0.2,
    retirementAge: 60,
    initialPortfolio: 500000,
    withdrawal: { type: 'fixed_amount', amount: 180000 },
    allocation: { sp500: 0.35, intlStock: 0.2, bond: 0.2, gold: 0.1, cash: 0.1, reits: 0.05 },
  },
  moderate: {
    id: 'moderate',
    name: 'Moderate',
    emoji: 'Balance',
    description: 'Baseline Manila preset aligned to the researched MVP defaults.',
    tagline: 'Manila MVP baseline',
    annualIncome: 540000,
    annualExpense: 360000,
    annualContribution: 100000,
    savingsRate: 0.19,
    retirementAge: 65,
    initialPortfolio: 1200000,
    withdrawal: { type: 'fixed_rate', rate: 0.04 },
    allocation: { sp500: 0.35, intlStock: 0.25, bond: 0.2, gold: 0.05, cash: 0.1, reits: 0.05 },
  },
  comfortable: {
    id: 'comfortable',
    name: 'Comfortable',
    emoji: 'Metro',
    description: 'Professional Manila household with higher rent tolerance and steady accumulation.',
    tagline: 'Urban professional track',
    annualIncome: 900000,
    annualExpense: 600000,
    annualContribution: 180000,
    savingsRate: 0.2,
    retirementAge: 62,
    initialPortfolio: 4000000,
    withdrawal: { type: 'fixed_amount', amount: 600000 },
    allocation: { sp500: 0.35, intlStock: 0.25, bond: 0.2, gold: 0.05, cash: 0.05, reits: 0.1 },
  },
  lavish: {
    id: 'lavish',
    name: 'Lavish',
    emoji: 'Prime',
    description: 'Central Manila high-spend lifestyle with limited savings headroom.',
    tagline: 'High-spend city core',
    annualIncome: 1600000,
    annualExpense: 1100000,
    annualContribution: 120000,
    savingsRate: 0.08,
    retirementAge: 67,
    initialPortfolio: 1500000,
    withdrawal: { type: 'fixed_amount', amount: 1100000 },
    allocation: { sp500: 0.45, intlStock: 0.2, bond: 0.1, gold: 0.05, cash: 0.1, reits: 0.1 },
  },
  fire_lean: {
    id: 'fire_lean',
    name: 'Lean FIRE',
    emoji: 'FIRE',
    description: 'Aggressive Manila savings path aimed at early retirement on a lean budget.',
    tagline: 'Early exit, low burn',
    annualIncome: 650000,
    annualExpense: 240000,
    annualContribution: 260000,
    savingsRate: 0.4,
    retirementAge: 45,
    initialPortfolio: 1200000,
    withdrawal: { type: 'fixed_rate', rate: 0.035 },
    allocation: { sp500: 0.45, intlStock: 0.3, bond: 0.1, gold: 0.05, cash: 0, reits: 0.1 },
  },
  fire_fat: {
    id: 'fire_fat',
    name: 'Fat FIRE',
    emoji: 'FIRE+',
    description: 'High-income Manila accumulation path targeting an early but comfortable retirement.',
    tagline: 'Early exit, wide margin',
    annualIncome: 2400000,
    annualExpense: 900000,
    annualContribution: 1000000,
    savingsRate: 0.42,
    retirementAge: 45,
    initialPortfolio: 6000000,
    withdrawal: { type: 'fixed_amount', amount: 900000 },
    allocation: { sp500: 0.4, intlStock: 0.25, bond: 0.15, gold: 0.05, cash: 0, reits: 0.15 },
  },
}

export const LIFESTYLE_PRESETS_PH_CEBU: LifestylePresetMap = {
  frugal: {
    id: 'frugal',
    name: 'Frugal',
    emoji: 'Saver',
    description: 'Lower-cost Cebu setup with conservative spending and small but steady savings.',
    tagline: 'Lean regional budget',
    annualIncome: 240000,
    annualExpense: 150000,
    annualContribution: 35000,
    savingsRate: 0.15,
    retirementAge: 60,
    initialPortfolio: 350000,
    withdrawal: { type: 'fixed_amount', amount: 150000 },
    allocation: { sp500: 0.35, intlStock: 0.2, bond: 0.2, gold: 0.1, cash: 0.1, reits: 0.05 },
  },
  moderate: {
    id: 'moderate',
    name: 'Moderate',
    emoji: 'Balance',
    description: 'Baseline Cebu preset aligned to the researched MVP defaults.',
    tagline: 'Cebu MVP baseline',
    annualIncome: 420000,
    annualExpense: 240000,
    annualContribution: 80000,
    savingsRate: 0.19,
    retirementAge: 65,
    initialPortfolio: 1000000,
    withdrawal: { type: 'fixed_rate', rate: 0.04 },
    allocation: { sp500: 0.35, intlStock: 0.25, bond: 0.2, gold: 0.05, cash: 0.1, reits: 0.05 },
  },
  comfortable: {
    id: 'comfortable',
    name: 'Comfortable',
    emoji: 'Coast',
    description: 'Upper-middle Cebu lifestyle with better savings leverage than Manila.',
    tagline: 'Regional growth track',
    annualIncome: 720000,
    annualExpense: 420000,
    annualContribution: 150000,
    savingsRate: 0.21,
    retirementAge: 62,
    initialPortfolio: 3000000,
    withdrawal: { type: 'fixed_amount', amount: 420000 },
    allocation: { sp500: 0.35, intlStock: 0.25, bond: 0.2, gold: 0.05, cash: 0.05, reits: 0.1 },
  },
  lavish: {
    id: 'lavish',
    name: 'Lavish',
    emoji: 'Prime',
    description: 'Premium Cebu lifestyle with central-city housing costs and thinner savings.',
    tagline: 'High-spend regional core',
    annualIncome: 1200000,
    annualExpense: 900000,
    annualContribution: 80000,
    savingsRate: 0.07,
    retirementAge: 67,
    initialPortfolio: 1200000,
    withdrawal: { type: 'fixed_amount', amount: 900000 },
    allocation: { sp500: 0.45, intlStock: 0.2, bond: 0.1, gold: 0.05, cash: 0.1, reits: 0.1 },
  },
  fire_lean: {
    id: 'fire_lean',
    name: 'Lean FIRE',
    emoji: 'FIRE',
    description: 'Cebu early-retirement path built around a lower long-run expense base.',
    tagline: 'Early exit, low burn',
    annualIncome: 500000,
    annualExpense: 220000,
    annualContribution: 160000,
    savingsRate: 0.32,
    retirementAge: 45,
    initialPortfolio: 1000000,
    withdrawal: { type: 'fixed_rate', rate: 0.035 },
    allocation: { sp500: 0.45, intlStock: 0.3, bond: 0.1, gold: 0.05, cash: 0, reits: 0.1 },
  },
  fire_fat: {
    id: 'fire_fat',
    name: 'Fat FIRE',
    emoji: 'FIRE+',
    description: 'High-income Cebu path aimed at retiring early with a larger comfort buffer.',
    tagline: 'Early exit, wide margin',
    annualIncome: 1800000,
    annualExpense: 700000,
    annualContribution: 700000,
    savingsRate: 0.39,
    retirementAge: 45,
    initialPortfolio: 5000000,
    withdrawal: { type: 'fixed_amount', amount: 700000 },
    allocation: { sp500: 0.4, intlStock: 0.25, bond: 0.15, gold: 0.05, cash: 0, reits: 0.15 },
  },
}

export function getPhilippinesLifestylePresets(region: Region): LifestylePresetMap {
  return region === 'ph-cebu' ? LIFESTYLE_PRESETS_PH_CEBU : LIFESTYLE_PRESETS_PH_MANILA
}

export function getPhilippinesLifestyleList(region: Region): LifestylePreset[] {
  return Object.values(getPhilippinesLifestylePresets(region))
}
